require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe AlertsController do

  def mock_alert(stubs={})
    @mock_alert ||= mock_model(Alert, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all alerts as @alerts" do
      Alert.stub(:all) { [mock_alert] }
      get :index
      assigns(:alerts).should eq([mock_alert])
    end
  end

  describe "GET show" do
    it "assigns the requested alert as @alert" do
      Alert.stub(:find).with("37") { mock_alert }
      get :show, :id => "37"
      assigns(:alert).should be(mock_alert)
    end
  end

  describe "GET new" do
    it "assigns a new alert as @alert" do
      Alert.stub(:new) { mock_alert }
      get :new
      assigns(:alert).should be(mock_alert)
    end
  end

  describe "GET edit" do
    it "assigns the requested alert as @alert" do
      Alert.stub(:find).with("37") { mock_alert }
      get :edit, :id => "37"
      assigns(:alert).should be(mock_alert)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created alert as @alert" do
        Alert.stub(:new).with({'these' => 'params'}) { mock_alert(:save => true) }
        post :create, :alert => {'these' => 'params'}
        assigns(:alert).should be(mock_alert)
      end

      it "redirects to the created alert" do
        Alert.stub(:new) { mock_alert(:save => true) }
        post :create, :alert => {}
        response.should redirect_to(alert_url(mock_alert))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved alert as @alert" do
        Alert.stub(:new).with({'these' => 'params'}) { mock_alert(:save => false) }
        post :create, :alert => {'these' => 'params'}
        assigns(:alert).should be(mock_alert)
      end

      it "re-renders the 'new' template" do
        Alert.stub(:new) { mock_alert(:save => false) }
        post :create, :alert => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested alert" do
        Alert.stub(:find).with("37") { mock_alert }
        mock_alert.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :alert => {'these' => 'params'}
      end

      it "assigns the requested alert as @alert" do
        Alert.stub(:find) { mock_alert(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:alert).should be(mock_alert)
      end

      it "redirects to the alert" do
        Alert.stub(:find) { mock_alert(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(alert_url(mock_alert))
      end
    end

    describe "with invalid params" do
      it "assigns the alert as @alert" do
        Alert.stub(:find) { mock_alert(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:alert).should be(mock_alert)
      end

      it "re-renders the 'edit' template" do
        Alert.stub(:find) { mock_alert(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested alert" do
      Alert.stub(:find).with("37") { mock_alert }
      mock_alert.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the alerts list" do
      Alert.stub(:find) { mock_alert }
      delete :destroy, :id => "1"
      response.should redirect_to(alerts_url)
    end
  end

end
